version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-uni-app
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - uni_network
    nginx:
        image: nginx:latest
        container_name: nginx-uni-server
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - uni_network

    mysql:
        image: mysql:8.0
        container_name: mysql-uni
        environment:
            MYSQL_ROOT_PASSWORD: "@Dat12345"
            MYSQL_DATABASE: school
        ports:
            - "3307:3307"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - uni_network

volumes:
    db_data:
networks:
    uni_network:
        driver: bridge
